---
- name: Create Bookinfo Project
  k8s:
    definition:
      apiVersion: project.openshift.io/v1
      kind: Project
      metadata:
        name: bookinfo
        display-name: "Bookinfo Project"
- name: Add Bookinfo to SMMR
  k8s:
    definition:
      apiVersion: maistra.io/v1
      kind: ServiceMeshMemberRoll
      metadata:
        name: default
        namespace: istio-system
      spec:
        members:
          # a list of projects joined into the service mesh
          - bookinfo
- name: Ensure bookinfo Directory Exists
  file: 
    path: "bookinfo"
    state: directory
    recurse: yes
- name: Copy Bookinfo Files to Remote Host
  copy: 
    src: "{{ item }}"
    dest: bookinfo/
    owner: sscaling-redhat.com
    group: users
    mode: '0750'
  with_fileglob:
    - bookinfo/*     
- name: Deploy Bookinfo Application
  k8s:
    state: present
    src: bookinfo/bookinfo.yaml
    namespace: bookinfo     
- name: Create Ingress Gateway
  k8s:
    state: present
    src: bookinfo/bookinfo-gateway.yaml
    namespace: bookinfo     
- name: Apply Destination Rules
  k8s:
    state: present
    src: bookinfo/destination-rule-all-mtls.yaml
    namespace: bookinfo